// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByGr_bUu_5R2zVxhhAWiqF2RlxGL4rIQQ',
    appId: '1:192750202235:web:31d8626c589f8fb54ee1de',
    messagingSenderId: '192750202235',
    projectId: 'sipakarena',
    authDomain: 'sipakarena.firebaseapp.com',
    storageBucket: 'sipakarena.firebasestorage.app',
    measurementId: 'G-E4CJGWZ637',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3dIkMm9iP5R5Erw39iOVya5L4nz7RyhE',
    appId: '1:192750202235:android:8b2a55e72586b0ce4ee1de',
    messagingSenderId: '192750202235',
    projectId: 'sipakarena',
    storageBucket: 'sipakarena.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf2BJyKR6npOQP1BWah4dp_4gj9kHwjjI',
    appId: '1:192750202235:ios:9d3f2ce98785ec1c4ee1de',
    messagingSenderId: '192750202235',
    projectId: 'sipakarena',
    storageBucket: 'sipakarena.firebasestorage.app',
    iosBundleId: 'com.example.sipakarena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf2BJyKR6npOQP1BWah4dp_4gj9kHwjjI',
    appId: '1:192750202235:ios:9d3f2ce98785ec1c4ee1de',
    messagingSenderId: '192750202235',
    projectId: 'sipakarena',
    storageBucket: 'sipakarena.firebasestorage.app',
    iosBundleId: 'com.example.sipakarena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByGr_bUu_5R2zVxhhAWiqF2RlxGL4rIQQ',
    appId: '1:192750202235:web:b1023682ac93ea5d4ee1de',
    messagingSenderId: '192750202235',
    projectId: 'sipakarena',
    authDomain: 'sipakarena.firebaseapp.com',
    storageBucket: 'sipakarena.firebasestorage.app',
    measurementId: 'G-43X5VFGM69',
  );

}